# Generated by Django 3.0.5 on 2020-04-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19Ca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('pruid', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('prname', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('prnameFR', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('numconf', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('numprob', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('numdeaths', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('numtotal', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('numtested', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('numrecover', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('percentrecover', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('ratetested', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('numtoday', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('percentoday', models.CharField(blank=True, default=None, max_length=32, null=True)),
            ],
        ),
    ]
